language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - "make check"
after_success:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] && npm install istanbul codecov.io && ./node_modules/.bin/istanbul cover ./node_modules/.bin/tape test/*.js && cat coverage/lcov.info | ./node_modules/.bin/codecov'
