language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - "make check"
after_success:
  - "./node_modules/.bin/istanbul cover ./node_modules/bin/tape test/*.js"
  - "cat coverage/lcov.info | ./node_modules/.bin/codecov"
